# Generated by Django 3.1.7 on 2021-03-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='TÍTULO')),
                ('atividades', models.TextField(blank=True, null=True, verbose_name='RESPONSABILIDADES E ATRIBUIÇÕES')),
                ('requisitos', models.TextField(blank=True, null=True, verbose_name='REQUISITOS E QUALIFICAÇÕES')),
                ('destaques', models.TextField(blank=True, null=True, verbose_name='VOCÊ SE DESTACA SE TIVER')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-ativo'],
            },
        ),
    ]
