# Generated by Django 3.1.7 on 2021-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assinaturas_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assinatura',
            options={},
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='atividades',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='destaques',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='requisitos',
        ),
        migrations.RemoveField(
            model_name='assinatura',
            name='titulo',
        ),
        migrations.AddField(
            model_name='assinatura',
            name='email',
            field=models.TextField(blank=True, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='nome',
            field=models.TextField(blank=True, null=True, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='setor',
            field=models.TextField(blank=True, null=True, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='assinatura',
            name='telefone',
            field=models.TextField(blank=True, null=True, verbose_name='Telefone'),
        ),
    ]
